# frozen_string_literal: true

source "https://rubygems.org"

gem "allure-cucumber", "2.14.5"
gem "cucumber", "5.2"
gem "capybara", "3.33"
gem "selenium-webdriver"
gem "rspec", "3.10"
gem "faker"
gem "mongo", "2.13.1"
gem "httparty", "0.18.1"
