require "digest/md5"

require_relative "features/support/libs/mongo"

def to_md5(pass)
  return Digest::MD5.hexdigest(pass)
end

task :test do
    puts "Executando uma tarefa de teste"
end

task :local_seeds do

    CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/local.yml"))

    users = [
        {name: "Roberto Carlos",  email: "betao@hotmail.com",    password: to_md5("pwd123")},
        {name: "Fernando Papito", email: "fernando@gmail.com",   password: to_md5("pwd123")},
        {name: "Anderson Silva",  email: "spider@hotmail.com",   password: to_md5("pwd123")},
        {name: "João anunciante",email: "joao@anunciante.com",  password: to_md5("pwd123")},
        {name: "Maria locataria",email: "maria@locataria.com",  password: to_md5("pwd123")},        
    ]

    MongoDB.new.drop_danger
    MongoDB.new.insert_users(users)
    
    #sh "cucumber"
    #para rodar o comando acima deve ser execitado o comando
    #rake local_seeds 
end

task :hmg_seeds do

    CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/hmg.yml"))

    users = [
        {name: "Roberto Carlos", email: "betao@hotmail.com",    password: to_md5("pwd123")},
        {name: "Fernando Papito",email: "fernando@gmail.com",   password: to_md5("pwd123")}, 
        {name: "João anunciante",email: "joao@anunciante.com",  password: to_md5("pwd123")},
        {name: "Maria locataria",email: "maria@locataria.com",  password: to_md5("pwd123")}, 
    ]

    MongoDB.new.drop_danger
    MongoDB.new.insert_users(users)

    sh "cucumber"
end